# Generated by Django 3.1.7 on 2021-03-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='channels',
            new_name='Channel',
        ),
    ]
