# Generated by Django 3.1.7 on 2021-03-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='channel_logo',
        ),
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
    ]
