# Generated by Django 3.1.7 on 2021-03-23 06:53

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210323_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discordvideo', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
