# Generated by Django 3.1.7 on 2021-03-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_desc',
            field=models.CharField(max_length=100000000000),
        ),
    ]
